### ISSUE TITLE
v11 support?

### ISSUE THREAD

**Issue by webhead9241** [hiddenkrypt/lancer-combat-banner#3]
Hi, love this module! Since migrating to v11 with the new Lancer 2.0 module, I noticed that the subheading now reads "[///]" for all combatants, as opposed to showing class/template for NPCS and pilot names for PCs. I'm wondering if this is an issue with the v11 workflow, and if so, whether there are plans to update? Thank you for your time!

**Comment by Glandulf** [comment]
I have the same problem, without having installed previous version, so I've only known the [///] text. I might also add that if I setup the module to use User Color, all the banners appear grey.
(All my players are Observers of all mechs and pilots, I was wondering if this could conflict or not ?)
